// flow-typed signature: 6237d11cd755e7998358600849c123b2
// flow-typed version: <<STUB>>/humanize-duration_v^3.12.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'humanize-duration'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'humanize-duration' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'humanize-duration/humanize-duration' {
  declare module.exports: any;
}

// Filename aliases
declare module 'humanize-duration/humanize-duration.js' {
  declare module.exports: $Exports<'humanize-duration/humanize-duration'>;
}
