// flow-typed signature: c9e21ce134236a8c52d08a857902eec2
// flow-typed version: <<STUB>>/md5_v2.2.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'md5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'md5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'md5/md5' {
  declare module.exports: any;
}

declare module 'md5/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'md5/md5.js' {
  declare module.exports: $Exports<'md5/md5'>;
}
declare module 'md5/test.js' {
  declare module.exports: $Exports<'md5/test'>;
}
