// flow-typed signature: 853554b4598da5c3ab857ab18e535e43
// flow-typed version: <<STUB>>/track-duration_v0.1.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'track-duration'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'track-duration' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'track-duration/dist/index' {
  declare module.exports: any;
}

declare module 'track-duration/dist/timeParser' {
  declare module.exports: any;
}

declare module 'track-duration/dist/utils/helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'track-duration/dist/index.js' {
  declare module.exports: $Exports<'track-duration/dist/index'>;
}
declare module 'track-duration/dist/timeParser.js' {
  declare module.exports: $Exports<'track-duration/dist/timeParser'>;
}
declare module 'track-duration/dist/utils/helpers.js' {
  declare module.exports: $Exports<'track-duration/dist/utils/helpers'>;
}
